### ISSUE TITLE
Changes to 'the Bore'

### ISSUE THREAD

**Issue by UncleTallest** [OhMyTallest-Productions/Arthian-Map#3]
As the Bore is a name from a David Eddings novel, we need to change this to prevent infringing on the IP of others. While we do this we should lay down some real data on current flow, it's changes with the seasons, and it's effects on the areas along it's banks.

**Comment by temujin9** [comment]
Eh? The term is very generic, and it's not used for the same meaning, and it is used in other fantasy (Wheel of Time) similarly without complaint. I think you're safe.

**Comment by JerryWJackson** [comment]
The Bore is the same thing in both of them at a high level, a narrowing of the land in a flowing body of water. Ergo, my worries. However, I do agree that if it is used in other fantasy then we should be safe.
